spring:
  ai:
    openai:
      api-key: sk-fdeb5cb9b141473ca196615ed8537df0
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: deepseek-v3

      audio:
        speech:
          base-url: https://dashscope.aliyuncs.com/compatible-mode
          options:
            model: cosyvoice-v2
            voice: longyingcui