server:
  port: 9000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mxzero_common
    username: postgres
    password: postgres
  data:
    redis:
      host: localhost
      port: 6379
      password: helloredis
      lettuce:
        pool:
          min-idle: 2
          max-active: 4
          max-wait: 20000
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 1666395717373937
          google:
            clientId: 371132010531-g2fsovcnl9dglvqqo3qpuvq4bn6tedid.apps.googleusercontent.com
            clientSecret: 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
          github:
            clientId: Ov23lilHVzypKogk2jSA
            clientSecret: d6339dde0fc517ec6edf73434d316e2513206bd0
          qq:
            provider: qq
            clientId: 102019868
            clientSecret: GUWLwLYZP2RcbVDj
            authorizationGrantType: authorization_code
            redirectUri: http://local.mxzero.top/login/oauth2/code/qq
          weibo:
            provider: weibo
            clientId: 2459617706
            clientSecret: 0da8b21da070f8c5cad17e409691741e
            authorizationGrantType: authorization_code
            redirectUri: http://local.mxzero.top/login/oauth2/code/weibo

        provider:
          qq:
            authorizationUri: https://graph.qq.com/oauth2.0/authorize
            tokenUri: https://graph.qq.com/oauth2.0/token
            userInfoUri: https://graph.qq.com/oauth2.0/me
            userNameAttribute: openid
          weibo:
            authorizationUri: https://api.weibo.com/oauth2/authorize
            tokenUri: https://api.weibo.com/oauth2/access_token
            userInfoUri: https://api.weibo.com/2/users/show.json
            userNameAttribute: id
  mail:
    host: smtp.qq.com
    port: 465
    username: qingfeng1222@qq.com
    password: umecwglltuufbaeb
    default-encoding: UTF-8
    properties:
      company:
        name: Your Company
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
logging:
  level:
    top.mxzero: debug
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
