version: "3.8"

services:
  app:
    image: mxzero-common-web
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - mxzero-filestore-data:/data/filestore

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mxzero_common
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - mxzero-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    volumes:
      - mxzero-redis-data:/data

volumes:
  mxzero-filestore-data:
  mxzero-postgres-data:
  mxzero-redis-data: