spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:postgresql://localhost:5432/mxzero_common
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ssXXX
  mail:
    host: smtp.qq.com
    port: 465
    username: qingfeng1222@qq.com
    password: umecwglltuufbaeb
    default-encoding: UTF-8
    properties:
      company:
        name: Your Company
      mail:
        smtp:
          ssl:
            enable: true
          auth: true

mxzero:
  jwt:
    expire: 7200
    issuer: http://mxzero.top
    secret: jwt-dev
  oss:
    type: qiniu
    access-key: oavSaZ7G1q4ZOxacfhby7R2ZgHym5JlbwPsRF6it
    secret-key: PyISYsr4ywAdP9vmtZANSqdjNM_6FFQX5fBwTlh3
    endpoint: store.mxzero.top
    secret: false
    bucket-name: mxzero-store

logging:
  level:
    org.springframework.security: DEBUG