spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mail:
    host: smtp.qq.com
    port: 465
    username: qingfeng1222@qq.com
    password: umecwglltuufbaeb
    default-encoding: UTF-8
    properties:
      company:
        name: 趣语星伴
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

mxzero:
  alipay:
    appid: 9021000123615029
    gateway-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
    alipay-public-key: classpath:/alipay/alipay_public_key.txt
    app-private-key-path: classpath:/alipay/alipay_app_private_key.txt
  jwt:
    expire: 2592000
    issuer: http://mxzero.top
    secret: ed8f07de-b628-49d5-a423-062d20e19907
  security:
    wechat:
      biz:
        appid: wx9cc9c76a79009543
        app-secret: f6b3f10f638004cb24eb23cadf60011a
        token: 381746E471C444E089B19FE12027BBD3
        aes-key: WtrRxen3j5Cyovu8Ed5hENDNLcDju6zUlohrpVI3h0G
  oss:
    type: qiniu
    access-key: oavSaZ7G1q4ZOxacfhby7R2ZgHym5JlbwPsRF6it
    secret-key: PyISYsr4ywAdP9vmtZANSqdjNM_6FFQX5fBwTlh3
    endpoint: qiniu.talkiestar.cn
    secret: false
    bucket-name: talkiestar

#logging:
#  level:
#    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus