server:
  port: 80
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mxzero_common
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss


mxzero:
  jwt:
    access: 72000
    refresh: 864000
    issuer: http://mxzero.top
  oss:
    type: qiniu
    access-key: JZC3y5EuQRx78LFmEeENRVdcEWNUCIzmgF8a7dTp
    secret-key: nFIdeB9QWtY2CjgecW781S7VU54Zc-rOyC7r59dv
    endpoint: image.zkodoo.cc
    secret: true
    bucket-name: zkodoo

logging:
  level:
    org.springframework.security: DEBUG