spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mxzero_common
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  data:
    redis:
      host: echovoid.top
      port: 26409
      password: helloredis

mxzero:
  filestore:
    type: local
    local:
      path: D:\\filestore