spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:5432/mxzero_common
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mail:
    host: smtp.qq.com
    port: 465
    username: qingfeng1222@qq.com
    password: umecwglltuufbaeb
    default-encoding: UTF-8
    properties:
      company:
        name: 趣语星伴
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
  ai:
    mcp:
      server:
        name: mxzero-common-mcp
        version: 0.0.1
    openai:
      api-key: sk-fdeb5cb9b141473ca196615ed8537df0
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: deepseek-v3
mxzero:
  openai:
    api-key: sk-fdeb5cb9b141473ca196615ed8537df0
    base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
    chat:
      model: qwen-turbo-latest
      temperature: 1.0
  jwt:
    expire: 2592000
    issuer: http://mxzero.top
    secret: ed8f07de-b628-49d5-a423-062d20e19907
  security:
    wechat:
      biz:
        appid: wx9cc9c76a79009543
        app-secret: f6b3f10f638004cb24eb23cadf60011a
        token: 381746E471C444E089B19FE12027BBD3
        aes-key: WtrRxen3j5Cyovu8Ed5hENDNLcDju6zUlohrpVI3h0G
  oss:
    #      type: ali
    #      access-key: LTAI5tCb2roFbwLHjjt5h4o2
    #      secret-key: Nc4xdBIYSSOvYJaYDNu07v38wJxoQH
    #      endpoint: oss-cn-hangzhou.aliyuncs.com
    #      secret: true
    #      bucket-name: odoo-filestore
    type: qiniu
    access-key: oavSaZ7G1q4ZOxacfhby7R2ZgHym5JlbwPsRF6it
    secret-key: PyISYsr4ywAdP9vmtZANSqdjNM_6FFQX5fBwTlh3
    endpoint: qiniu.talkiestar.cn
    secret: false
    bucket-name: talkiestar
#    type: minio
#    access-key: uoxBxPoYTvTggt89Fklf
#    secret-key: CY5vKH737eOLqf4seGsxhJ96ao1K7RltkMh0hkjO
#    endpoint: talkiestar.cn:9000
#    secret: false
#    bucket-name: first
  tts:
    app-key: 496600955eb048d1
    app-secret: NkaR8fhbGy4063s9BYk3n4CZgAU651Hi
logging:
  level:
    org.springframework.security: DEBUG