server:
  port: 80
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mxzero_common
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23lilHVzypKogk2jSA
            clientSecret: d6339dde0fc517ec6edf73434d316e2513206bd0
          qq:
            provider: qq
            clientId: 102019868
            clientSecret: GUWLwLYZP2RcbVDj
            authorizationGrantType: authorization_code
            redirectUri: http://local.mxzero.top/login/oauth2/code/qq
          weibo:
            provider: weibo
            clientId: 2459617706
            clientSecret: 0da8b21da070f8c5cad17e409691741e
            authorizationGrantType: authorization_code
            redirectUri: http://local.mxzero.top/login/oauth2/code/weibo
        provider:
          qq:
            authorizationUri: https://graph.qq.com/oauth2.0/authorize
            tokenUri: https://graph.qq.com/oauth2.0/token?fmt=json
            userInfoUri: https://graph.qq.com/oauth2.0/me?fmt=json
            userNameAttribute: openid
          weibo:
            authorizationUri: https://api.weibo.com/oauth2/authorize
            tokenUri: https://api.weibo.com/oauth2/access_token
            userInfoUri: https://api.weibo.com/oauth2/get_token_info
            userNameAttribute: uid


mxzero:
  jwt:
    access: 72000
    refresh: 864000
    issuer: http://mxzero.top
  oss:
    type: qiniu
    access-key: JZC3y5EuQRx78LFmEeENRVdcEWNUCIzmgF8a7dTp
    secret-key: nFIdeB9QWtY2CjgecW781S7VU54Zc-rOyC7r59dv
    endpoint: image.zkodoo.cc
    secret: true
    bucket-name: zkodoo

logging:
  level:
    org.springframework.security: DEBUG