spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/echovoid_common
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  data:
    redis:
      host: localhost
      port: 26409
      password: helloredis

echovoid:
  filestore:
    type: local
    local:
      path: /data/local_filestore