spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mail:
    host: smtp.qq.com
    port: 465
    username: example@qq.com
    password: 32........32
    default-encoding: UTF-8
    properties:
      company:
        name: EchoVoid
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

echovoid:
  alipay:
    appid: 90.......9
    gateway-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
    alipay-public-key: classpath:/alipay/alipay_public_key.txt
    app-private-key-path: classpath:/alipay/alipay_app_private_key.txt
  jwt:
    expire: 2592000
    issuer: http://echovoid.top
    secret: ed8f07de-b628-49d5-a423-062d20e19907
  security:
    wechat:
      biz:
        appid: wx9.......43
        app-secret: f6.............a
        token: 38...................BD3
        aes-key: WtrRx..................h0G
  oss:
    type: qiniu
    access-key: oa..................F6it
    secret-key: PyI........................h3
    endpoint: qiniu.talkiestar.cn
    secret: false
    bucket-name: ta....ar

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus