spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/primary_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO