server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oauth2
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.transaction.jta.platform: org.hibernate.service.jta.JtaPlatform
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23lilHVzypKogk2jSA
            clientSecret: d6339dde0fc517ec6edf73434d316e2513206bd0
          qq:
            provider: qq
            clientId: 102019868
            clientSecret: GUWLwLYZP2RcbVDj
            authorizationGrantType: authorization_code
            redirectUri: http://local.mxzero.top/login/oauth2/code/qq
          weibo:
            provider: weibo
            clientId: 2459617706
            clientSecret: 0da8b21da070f8c5cad17e409691741e
            authorizationGrantType: authorization_code
            redirectUri: http://local.mxzero.top/login/oauth2/code/weibo
        provider:
          qq:
            authorizationUri: https://graph.qq.com/oauth2.0/authorize
            tokenUri: https://graph.qq.com/oauth2.0/token?fmt=json
            userInfoUri: https://graph.qq.com/oauth2.0/me?fmt=json
            userNameAttribute: openid
          weibo:
            authorizationUri: https://api.weibo.com/oauth2/authorize
            tokenUri: https://api.weibo.com/oauth2/access_token
            userInfoUri: https://api.weibo.com/oauth2/get_token_info
            userNameAttribute: uid